<?php namespace ProcessWire;

class SelectizeAll extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Selectize All',
			'summary' => 'Uses Selectize on all InputfieldSelect fields in the ProcessWire admin.',
			'version' => '0.1.0',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/SelectizeAll',
			'icon' => 'chevron-down',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0, PHP>=5.4.0',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		// Load Selectize
		/** @var JqueryUI $jQueryUI */
		$jQueryUI = $this->wire()->modules->get('JqueryUI');
		$jQueryUI->use('selectize');

		// Load assets
		$config = $this->wire()->config;
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->styles->add($config->urls->$this . "$this.css?v=$version");
		$config->scripts->add($config->urls->$this . "$this.js?v=$version");

		$this->addHookAfter('InputfieldSelect::renderReadyHook', $this, 'afterSelectRenderReady');
	}

	/**
	 * After InputfieldSelect::renderReadyHook
	 *
	 * @param HookEvent $event
	 */
	protected function afterSelectRenderReady(HookEvent $event) {
		/** @var InputfieldSelect $inputfield */
		$inputfield = $event->object;
		// Return early if some other inputfield type is extending InputfieldSelect
		if($inputfield->className !== 'InputfieldSelect') return;
		// Add class
		if($inputfield->hasInputfield) {
			// InputfieldPage using InputfieldSelect
			$inputfield->hasInputfield->wrapClass = 'sa-selectize';
		} else {
			$inputfield->wrapClass = 'sa-selectize';
		}
	}

}
